### ISSUE TITLE
Error Message on Mac OS X El Capitan

### ISSUE THREAD

**Issue by fredericcogny** [amcphail/plot-gtk3#6]
The below code fails at run-time with the following message

```
~/git/Haskell/Gtk3Test » stack exec Gtk3Test-exe                                                                                                                                    Fred@Freds-Mac|0:47:11|
2016-02-19 00:47:34.910 Gtk3Test-exe[54150:993438] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead.
Gtk3Test-exe: SystemziGlibziMainLoop_drvi: interrupted
```

``` haskell
import           Numeric.LinearAlgebra.Data
import           Graphics.Rendering.Plot.HMatrix
import           Graphics.Rendering.Plot.Gtk
import           Graphics.Rendering.Plot.Render (OutputType(..))

someFunc :: IO ()
someFunc = do
  let x         = vector [1..10]
      y         = vector $ map (^2) [1..10]
  plotHandle    <- mplotH [x , y]
  writePlotHandle plotHandle PDF "Output.pdf" (200,200)
```

This issue seems to be 
- specific to retina display or el capitan (it works fine on another machine with the previous OS)
- coming from the underlying library gtk+3 where I found a similar bug logged: https://bugzilla.gnome.org/show_bug.cgi?id=749004

However I feel this should be treated as a warning and not an error since the PDF is actually generated fine in the current directory and the error message actually starts with the word _WARNING_

Not sure if that is something easy to change though but thanks in advance for looking at this

**Comment by amcphail** [comment]
Hi fredericcogny,

This looks to be a warning generated, as you identified, by the Glib library which is part of the gtk(3) suite.  It is not something I can access from within the plot-gtk3 library.

It looks like you have correctly identified the gtk bug.

Cheers,

Vivian
